支払グループ
atsuya02/dutch_account pull request #18
Opened 2022-08-04 14:11 UTC by atsuya02

2022-08-05 12:26 UTC, atsuya02 commented
@YuyaYoshioka 
レビューお願い

2022-08-05 14:26 UTC, YuyaYoshioka requested changes
レビューした

2022-08-05 14:26 UTC, YuyaYoshioka commented on server/openapi.yml
> +            $ref: "#/components/schemas/UserPaymentGroup"
[MUST]
PaymentGroup作るのに必要なのは、admin_idとnameだけでは？

2022-08-05 14:55 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2022-08-06 05:35 UTC, YuyaYoshioka approved these changes
LGTM

2022-08-06 05:39 UTC, merged