購入履歴API
atsuya02/dutch_account pull request #21
Opened 2022-08-06 06:10 UTC by atsuya02

2022-08-06 08:12 UTC, atsuya02 commented
@YuyaYoshioka 
レビューお願い

2022-08-06 12:35 UTC, YuyaYoshioka requested changes
レビューした

2022-08-06 12:35 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
[MUST]
path_parameterに`payment_group_id`いる？
`user_payment_group_id`だけで良いのでは？

2022-08-06 12:35 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
[MUST]
更新するのにPurchaseRecordを特定するには`purchase_record_id`だけあれば良いのでは？
`payment_group_id`いらなさそう

2022-08-06 12:35 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
[MUST]
同様に削除も`purchase_record_id`だけで良いのでは？

2022-08-06 13:04 UTC, atsuya02 commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
管理者で作るデータを制限したいと思ってこうしてたわ
例：
1. 管理者A…`user_payment_group_id`が`1`のユーザを持つ
2. 管理者B…`user_payment_group_id`が`2`のユーザを持つ
3. 管理者Aで`user_payment_group_id`が`2`のユーザでの購入履歴を作成しようとする
4. `payment_group`で管理者Aは`user_payment_group_id`が`2`のデータを持っていないことを判断してデータを作成できないようにする

`$ref: "#/components/parameters/AdminId"`で管理者ID渡した方がよい？

2022-08-06 13:15 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
認証のために常にadmin_idはcookieで送っているのでは？
1. PurchaseRecordを作成するために、user_payment_group_idをpath parameterで、admin_idをcookieで送る
2. UserPaymentGroupのpayment_group_idからPaymentGroupを取得する
3. 2で取得したPaymentGroupのadmin_idとcookieで送られてきたadmin_idが同一のものか確認する。同一でなければUnAuthorizedを返す
でいいと思っている。

2022-08-06 13:19 UTC, atsuya02 commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
なるほど、修正するわ
admin_idはcookieで一部でしか送ってなかったからそこも修正する

2022-08-06 13:22 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
`ADMIN`は今常にcookieで送られるのでは？
![image](https://user-images.githubusercontent.com/71418423/183250734-2e5d7972-cec7-4d49-a131-1e31f91df3d0.png)

右上のAuthorizeでADMIN設定すると、Try It Out でリクエストのcookieに入ってるよ

![image](https://user-images.githubusercontent.com/71418423/183250767-0c8482ef-ca5a-45d7-bf9d-2a4f38ad49b7.png)

2022-08-06 13:22 UTC, atsuya02 commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
admin_idをcookieで送るためには
```yaml
paramenters:
  - $ref: "#/components/parameters/AdminId"
```
を書く必要があると思ってたけど、
```yaml
security:
  - cookieAuth: []
```
を書いてるから必要ないって感じ？

2022-08-06 13:23 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
だと思ってる

2022-08-06 13:25 UTC, atsuya02 commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
GET /usersは
```yaml
paramenters:
  - $ref: "#/components/parameters/AdminId"
```
を直接書いてるわ
https://github.com/atsuya02/dutch_account/blob/7b6557f6486861114f413769c3234c92c0f3b01c/server/openapi.yml#L24-L25
PUT /users/{user_id}とかは書いてないから出てないと思う

2022-08-06 13:27 UTC, YuyaYoshioka commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
![image](https://user-images.githubusercontent.com/71418423/183250920-9a1ebf86-811f-46ed-8462-657b401860e4.png)

今回足したのにも出てる

2022-08-06 13:29 UTC, atsuya02 commented on server/openapi.yml
> +          $ref: "#/components/responses/InternalServerError"
curlの`ADMIN=111`のところか
必要なさそうだわmm
(GET /usersのparametersも消しておく)

2022-08-06 14:01 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2022-08-07 06:13 UTC, YuyaYoshioka reviewed
レビューした

2022-08-07 06:13 UTC, YuyaYoshioka commented on server/openapi.yml
> +      summary: 全購入履歴情報取得API
[IMO]
全購入履歴ではなさそう。支払いグループに紐づく全購入履歴とか？

2022-08-07 06:13 UTC, YuyaYoshioka commented on server/openapi.yml
> +  /purchase_records:
[SHOULD]
/user_payment_groups/{user_payment_group_id}/purchase_recors
の方が良さそう
user_payment_group_idはpath_parameterで渡す

2022-08-07 06:13 UTC, YuyaYoshioka commented on server/openapi.yml
> +  /purchase_records/{purchase_record_id}:
同上

2022-08-07 06:25 UTC, atsuya02 commented on server/openapi.yml
> +  /purchase_records:
グループに所属しているユーザの購入履歴をまとめて作成できるようにする予定なのでpathで渡すのは厳しそう
あと、よく考えたらここのURLは`/payment_groups/{payment_group_id}/purchase_records`のままで良かったかも

2022-08-07 06:28 UTC, YuyaYoshioka commented on server/openapi.yml
> +  /purchase_records:
なるほど。
`payment_group_id`って使う？
いらないなら、`user_payment_groups/purchase_records`とかでいい気がした。
あと、一括で購入履歴作成するなら、summaryとdescriptionも変えておいた方がいい。

2022-08-07 06:32 UTC, atsuya02 commented on server/openapi.yml
> +  /purchase_records:
`payment_group_id`は`user_payment_group_id`が対象のグループに含まれているかの確認で使うかな
summaryとdescriptionも修正しとく

2022-08-07 06:42 UTC, YuyaYoshioka commented on server/openapi.yml
> +  /purchase_records:
`user_payment_group_id`を指定した時点でそのUserPaymentGroupに紐づくPaymentGroupは一意にきまるのでは？
`/payment_groups/{payment_group_id}/purchase_records`だとPaymentGroupの親レコードに対してPurchaseRecordが子レコードになってしまって、リソースの意味が変わってしまう。

2022-08-07 06:52 UTC, atsuya02 commented on server/openapi.yml
> +  /purchase_records:
支払グループに所属するユーザを一覧で表示するのはフロントで行えばよくてサーバー側は関係ないのか(フロントとサーバでURL揃えるみたいなことを考えてしまっていた)
`user_payment_groups/purchase_records`で大丈夫そう

2022-08-07 06:55 UTC, atsuya02 commented on server/openapi.yml
> +  /purchase_records:
GETも`/payment_groups/{payment_group_id}/user_payment_groups/purchase_records`の方が良いか

2022-08-07 06:57 UTC, YuyaYoshioka commented on server/openapi.yml
> +  /purchase_records:
GETは、PaymentGroupに所属するUserPaymentGroupの全てのPurchaseRecordだから
`/payment_groups/{payment_group_id}/purchase_records`
で良さそう

2022-08-07 07:05 UTC, atsuya02 commented on server/openapi.yml
> +  /purchase_records/{purchase_record_id}:
PUTで`user_payment_group_id`を変えられるようにしようと思っていたけどその動作は微妙？

2022-08-07 08:49 UTC, YuyaYoshioka commented on server/openapi.yml
> +  /purchase_records/{purchase_record_id}:
変えても大丈夫な気がする

2022-08-07 11:08 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2022-08-07 11:30 UTC, YuyaYoshioka approved these changes
一箇所だけ確認お願い 🙏 
LGTM 👍 

（あくまで参考
複数の追加・更新などはURL変えるやり方もある。今回はとりあえずこのままで良さそう。
https://note.com/yamarkz/n/n41e9ac83c896#1awJv 
例えば、ユーザーを作成するときに、`POST /users`だと基本的にはユーザーを一つ作成することを意味するから、`users`でユーザーを複数作成すると判断ができない。）

2022-08-07 11:30 UTC, YuyaYoshioka commented on server/openapi.yml
> +                  example: 食材
[NITS]
ここら辺PurchaseRequestBody参照できそう

2022-08-07 11:31 UTC, YuyaYoshioka commented
ちなみにopenapiの定義ファイルはconflict頻度高いから、あらかじめ作っておくのはあんまりおすすめしない 😇

2022-08-07 12:24 UTC, atsuya02 commented on server/openapi.yml
> +                  example: 食材
ここ自分も共通化しようとしたけど今の状態やと出来なさそう
`PurchaseRecord`などの`schema`定義を使って
```yaml
PurchaseRecordsBody:
  description: リクエスト複数購入履歴情報
  content:
    application/json:
      schema:
        type: array
        items:
         $ref: "#/components/schemas/PurchaseRecord"
```
みたいな書き方を公式はしてたよ

`components/requestBodies`には
```yaml
application/json:
  schema:
    type: object
```
という記述があるからそのままは使えなさそう

`/components/schemas`に共通化用のschema作るのも微妙かなって思ってこのままにしてたわ

2022-08-07 14:45 UTC, YuyaYoshioka commented on server/openapi.yml
> +                  example: 食材
むしろ共通のshama作りたい。
PurchaseRecordのカラム変わったら、両方変えないといけない方が辛いと思う（書き換え忘れなど）

2022-08-07 15:07 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ
ついでに複数リソースのURLも修正した

2022-08-07 15:17 UTC, YuyaYoshioka approved these changes
LGTM

2022-08-07 15:37 UTC, merged