マイページ作成
atsuya02/dutch_account pull request #51
Opened 2022-10-03 14:49 UTC by atsuya02

2022-10-05 12:30 UTC, atsuya02 commented on client/src/hooks/useSignIn.ts
> +  }, [router]);
ドキュメント参照
https://nextjs.org/docs/api-reference/next/router#routerprefetch

2022-10-05 12:41 UTC, atsuya02 commented
@YuyaYoshioka 
レビューお願い

2022-10-06 12:49 UTC, YuyaYoshioka requested changes
レビューした

2022-10-06 12:49 UTC, YuyaYoshioka commented on client/src/hooks/useSignInUser.ts
> +const useSignInUser = () => {
[IMO]
名前が分かりにくいかも。サインインするhookに見えてしまう。useGetSignInUserとかでいい気がする。

2022-10-06 12:49 UTC, YuyaYoshioka commented on client/src/hooks/useSignInUser.ts
> +  const { data, error, isValidating } = useSWR<User, AxiosError<ResponseError>>(
[NITS]
AxiosError<ResponseError>をいろんなところで使ってるから，型定義して汎用化したい。

2022-10-06 12:49 UTC, YuyaYoshioka commented on client/src/pages/mypage.tsx
> +  useRequireLogin(isValidating, error);
[must]
useSignInUserのonErrorとかに書いた方がいい気がする。コンポーネントに関数を直書きすると，stateが更新されて再レンダリング走った時とかにも呼ばれるから，あんまりみないかな。

2022-10-06 12:49 UTC, YuyaYoshioka commented on client/src/hooks/useRequireLogin.ts
> +  }, [error, router, toast, isValidating]);
[MUST]
これってuseEffectとか使わなくても，errorを引数にとって，errorが401の時に，画面遷移させるって関数でいい気がする。

2022-10-08 00:45 UTC, YuyaYoshioka approved these changes
LGTM

2022-10-08 00:45 UTC, YuyaYoshioka commented on client/src/hooks/useSwrValue.ts
> +      }
[IMO]
このstatus codeを判定するコードもrequireLoginの中に入れた方がよいのでは？requireLoginにerrorを渡す意味がなくなってる気がする。
requireLoginの中でerrorに関する条件分岐を行う方がテストもしやすくなるし。

2022-10-08 00:45 UTC, YuyaYoshioka commented on client/src/pages/_app.tsx
> +      <SWRConfig value={swrValue}>
エラー処理の共通化いいね 😄

2022-10-08 03:34 UTC, merged